# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: justdo

before:
  hooks:
    - go mod tidy

builds:
  - id: justdo
    main: ./cmd/justdo
    binary: justdo
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: justdo-archives
    builds:
      - justdo
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums_{{ .Version }}.txt'

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: justdo
    repository:
      owner: atharvwasthere
      name: homebrew-tap
    commit_author:
      name: JustDO CI
      email: ci@users.noreply.github.com
    directory: Formula
    description: "JustDO — fast CLI to run your doers"
    homepage: "https://github.com/atharvwasthere/JustDO"
    install: |
      bin.install "justdo"
    test: |
      system "#{bin}/justdo", "--version"

scoops:
  - name: justdo
    repository:
      owner: atharvwasthere
      name: scoop-bucket
    commit_author:
      name: JustDO CI
      email: ci@users.noreply.github.com
    description: "JustDO — fast CLI to run your doers"
    homepage: "https://github.com/atharvwasthere/JustDO"
    license: MIT

release:
  github:
    owner: atharvwasthere
    name: JustDO
  draft: false
  prerelease: false
